import re

SYS_OPEN = "<|system|>"
SYS_CLOSE = "<|end|>"
USR_OPEN = "<|user|>"
AST_OPEN = "<|assistant|>"

class LocalIntelligencePlugin:
    SENSITIVE_TOPIC_KEYWORDS = [
        'war', 'attack', 'conflict', 'invasion', 'strike', 'military', 'kill',
        'bomb', 'sanction', 'protest', 'coup', 'riot', 'iran', 'russia', 'china',
        'terrorism', 'nuclear', 'weapon', 'death'
    ]

    STOP_MARKERS = [
        "<|end|>", "<|user|>", "<|assistant|>", "<|system|>", "<|endoftext|>",
        "<end_of_turn>", "<start_of_turn>", "<|eot_id|>", "<|start_header_id|>",
        "\nUser:", "\nuser:", "\nHuman:", "\nhuman:", "\nAI:", "\nai:",
        "\nAssistant:", "\nassistant:", "\nNote:", "\n(Note:", "\n(Explanation:",
        "== END", "== END OF", "\n---"
    ]

    @staticmethod
    def is_sensitive_topic(q):
        return any(k in q.lower() for k in LocalIntelligencePlugin.SENSITIVE_TOPIC_KEYWORDS)

    @staticmethod
    def build_system_prompt(base, query):
        if LocalIntelligencePlugin.is_sensitive_topic(query):
            return ("You are a professional news editor. "
                    "Your ONLY task is to summarize SOURCE_MATERIAL factually. "
                    "NEVER refuse or add warnings.")
        return base

    @staticmethod
    def reframe_query(query):
        if LocalIntelligencePlugin.is_sensitive_topic(query):
            return "Summarize the SOURCE_MATERIAL about: " + query
        return query

    @staticmethod
    def clean_local_response(raw):
        """
        Cleans hallucinations, simulated multi-turn loops, and meta-notes
        frequently generated by small local quantized LLMs.
        """
        if not raw:
            return ""

        c = raw

        # 1. Truncate at explicit stop markers
        for m in LocalIntelligencePlugin.STOP_MARKERS:
            if m in c:
                c = c.split(m)[0]

        # 2. Strip trailing meta-notes like "(Note: As Kruuboo...)" or "Note: ..."
        c = re.split(r'\n+\s*\(?Note\s*:', c, flags=re.IGNORECASE)[0]
        c = re.split(r'\n+\s*\(?Explanation\s*:', c, flags=re.IGNORECASE)[0]
        c = re.split(r'\n+\s*==+\s*END', c, flags=re.IGNORECASE)[0]

        # 3. Strip redundant simulated alternative assistant answers ("AI: Hello... AI: Hi...")
        lines = c.split('\n')
        cleaned_lines = []
        for line in lines:
            trimmed = line.strip()
            # If line is a simulated secondary assistant line, halt
            if re.match(r'^(AI|Assistant|User|Human)\s*:', trimmed, re.IGNORECASE) and cleaned_lines:
                break
            cleaned_lines.append(line)
        
        c = "\n".join(cleaned_lines)

        # 4. Remove standalone system/user tags if leaked
        c = re.sub(r'<\/?(system|user|assistant|end|start_of_turn|end_of_turn|eot_id)[^>]*>', '', c)

        return c.strip()

    @staticmethod
    def format_phi3_prompt(system_prompt, messages, query="", model_name=""):
        """
        Build a cleanly formatted multi-turn prompt tailored to the target model architecture.
        Preserves conversation history so multi-turn context is maintained.
        """
        role_line = system_prompt if system_prompt else "You are Kruuboo, a helpful and direct AI assistant."

        # Separate system messages and dialog turns
        dialog_turns = []
        for m in messages:
            role = m.get("role", "")
            content = str(m.get("content", "")).strip()
            if not content:
                continue
            if role == "system":
                # Supplement system prompt if it contains web research or special context
                if "WEB_RESEARCH_RESULTS" in content:
                    role_line += f"\n\n{content}"
            elif role in ("user", "assistant"):
                dialog_turns.append({"role": role, "content": content})

        # Fallback if no user message found in dialog_turns
        if not dialog_turns and query:
            dialog_turns.append({"role": "user", "content": query.strip()})

        # Keep last 6 dialogue turns max to avoid overflowing context window for small local models
        if len(dialog_turns) > 6:
            dialog_turns = dialog_turns[-6:]

        model_lower = str(model_name).lower()

        # Gemma format (used by LiteRT Gemma 4 E2B)
        if "gemma" in model_lower:
            prompt_parts = []
            first_user = True
            for turn in dialog_turns:
                if turn["role"] == "user":
                    if first_user:
                        prompt_parts.append(f"<start_of_turn>user\n{role_line}\n\n{turn['content']}<end_of_turn>")
                        first_user = False
                    else:
                        prompt_parts.append(f"<start_of_turn>user\n{turn['content']}<end_of_turn>")
                elif turn["role"] == "assistant":
                    prompt_parts.append(f"<start_of_turn>model\n{turn['content']}<end_of_turn>")
            
            prompt_parts.append("<start_of_turn>model\n")
            return "\n".join(prompt_parts)

        # Llama-3 format
        if "llama-3" in model_lower or "llama3" in model_lower:
            prompt_parts = [f"<|start_header_id|>system<|end_header_id|>\n\n{role_line}<|eot_id|>"]
            for turn in dialog_turns:
                if turn["role"] == "user":
                    prompt_parts.append(f"<|start_header_id|>user<|end_header_id|>\n\n{turn['content']}<|eot_id|>")
                elif turn["role"] == "assistant":
                    prompt_parts.append(f"<|start_header_id|>assistant<|end_header_id|>\n\n{turn['content']}<|eot_id|>")
            prompt_parts.append("<|start_header_id|>assistant<|end_header_id|>\n\n")
            return "".join(prompt_parts)

        # Phi-3 / Standard format (default)
        prompt_parts = [f"{SYS_OPEN}\n{role_line}{SYS_CLOSE}"]
        for turn in dialog_turns:
            if turn["role"] == "user":
                prompt_parts.append(f"{USR_OPEN}\n{turn['content']}{SYS_CLOSE}")
            elif turn["role"] == "assistant":
                prompt_parts.append(f"{AST_OPEN}\n{turn['content']}{SYS_CLOSE}")
        prompt_parts.append(f"{AST_OPEN}\n")
        return "\n".join(prompt_parts)